spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
