spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_ROOT_USER}}
    password: ${MYSQL_ROOT_PASSWORD}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#mybatis:
#  config-location: classpath:com.example.moneyAllocation/*.xml
