spring:
  datasource:
    url: jdbc:mysql://${HOST}:3306/${DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  jwtSecret: my-jwt-secret-keyphrase