CREATE SCHEMA IF NOT EXISTS ALLOCATION;
SET SCHEMA ALLOCATION;

CREATE TABLE USER(
    ID BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    NAME TEXT NOT NULL,
    NUM_FREE_TRANSFER INT NOT NULL,
    TRANSFER_FEE INT NOT NULL,
    OWNER_ID BIGINT NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES USER (ID)
);

CREATE TABLE regular_transfer (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  from_account BIGINT NOT NULL,
  to_account BIGINT NOT NULL,
  description TEXT NOT NULL,
  percentage BOOLEAN NOT NULL DEFAULT FALSE,
  amount INT UNSIGNED,
  ratio FLOAT,
  user_id BIGINT,
  FOREIGN KEY (from_account) REFERENCES account(id),
  FOREIGN KEY (to_account) REFERENCES account(id),
  FOREIGN KEY (user_id) REFERENCES user(id)
);


CREATE TABLE temporary_transfer (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  from_account BIGINT NOT NULL,
  to_account BIGINT NOT NULL,
  description TEXT NOT NULL,
  amount INT UNSIGNED NOT NULL,
  user_id BIGINT,
  FOREIGN KEY (from_account) REFERENCES account(id),
  FOREIGN KEY (to_account) REFERENCES account(id),
  FOREIGN KEY (user_id) REFERENCES user(id)
);
