CREATE SCHEMA IF NOT EXISTS ALLOCATION;
SET SCHEMA ALLOCATION;

CREATE TABLE USER(
    ID BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    NAME TEXT NOT NULL,
    NUM_FREE_TRANSFER INT NOT NULL,
    TRANSFER_FEE INT NOT NULL,
    OWNER_ID BIGINT NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES USER (ID)
);