name: Java CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Maven
      run: |
        if [ ! -d "/opt/apache-maven-3.5.2" ]; then
          wget https://archive.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz -P /tmp
          sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
          if [ -L /opt/maven ] ; then
            sudo rm /opt/maven
          fi
          sudo ln -s /opt/apache-maven-3.5.2 /opt/maven
        fi
        echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
        echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
        echo "PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Maven installation
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install
      
    - name: move jar to home dir
      run: mv ./allocation-api/allocation-api/target/moneyAllocation-0.0.1-SNAPSHOT.jar ~/
    

