name: Java CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: Verify Maven installation
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install

