name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          maven-version: '3.5.2'

      # Setup Maven Version
      - name: Set up Maven
        uses: actions/setup-maven@v1
        with:
          maven-version: '3.5.2'

      - name: local repo clean
        run: mvn dependency:purge-local-repository
      - name: Run Unit Tests
        run: mvn clean install

