name: Java CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup Maven
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz -P /tmp
          sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
          sudo ln -s /opt/apache-maven-3.5.2 /opt/maven
          sudo tee /etc/profile.d/maven.sh <<- END
            export JAVA_HOME=/usr/lib/jvm/default-java
            export M2_HOME=/opt/maven
            export MAVEN_HOME=/opt/maven
            export PATH=${M2_HOME}/bin:${PATH}
          END
          source /etc/profile.d/maven.sh

      - name: Verify Maven installation
        run: mvn -version

      - name: Build with Maven
        run: mvn test
#
#      - name: maven version check
#        run: mvn --version
#      - name: Run Unit Tests
#        run: mvn clean install
#

      #      - name: Set up JDK 17
      #        uses: actions/setup-java@v2
      #        with:
      #          java-version: '17'
      #          distribution: 'temurin'
      #          maven-version: '3.5.2'
